
(use-modules (annotation) (annotation main)
        (annotation gene-go)
        (annotation biogrid) 
        (annotation gene-pathway)
        (annotation functions)
        (annotation util)
        (annotation parser)
        (json))
(use-modules (opencog))

(define (loaf fn)
	(define start (current-time))
	(define ssz (count-all))
	(define path (string-append "/home/ubuntu/datasets/" fn))
	(define jnk (primitive-load path))
	(define elapse (- (current-time) start))
	(define delta (- (count-all) ssz))
	(define rate (/ delta elapse))
	(format #t "Took ~A secs to load ~A\n" elapse fn)
	(format #t "Loaded ~A atoms (~A per sec) space=~A\n" delta rate (count-all))
)

(loaf "ChEBI2Reactome_PE_Pathway.txt.scm")
(loaf "smpdb_protein.scm")
(loaf "NCBI2Reactome_PE_Pathway.txt.scm")
(loaf "uniprot2GO.scm")
(loaf "UniProt2Reactome_PE_Pathway.txt.scm")
(loaf "reactome.scm")
(loaf "GO_annotation.scm")
(loaf "entrez_to_protein.scm")
(loaf "current_symbols.scm")
(loaf "biogrid_gene_gene_174.scm")
(loaf "smpdb_chebi_wname.scm")
(loaf "biogridgene2uniprot.scm")
(loaf "GO_without_def.scm")
(loaf "current/ChEBI2Reactome_PE_Pathway.txt.scm")
(loaf "current/biogrid_gene_gene_3.5.177.scm")
(loaf "current/NCBI2Reactome_PE_Pathway.txt.scm")
(loaf "current/uniprot2GO.scm")
(loaf "current/UniProt2Reactome_PE_Pathway.txt.scm")
(loaf "current/reactome.scm")
(loaf "current/GO_annotation.scm")
(loaf "current/entrez_to_protein.scm")
(loaf "current/biogridgene2uniprot.scm")
(loaf "current/GO.scm")
